# Generated by Django 5.0.1 on 2024-02-04 18:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_choice_votes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='user_votes',
            field=models.ManyToManyField(related_name='voted_choices', to=settings.AUTH_USER_MODEL),
        ),
    ]
