# Generated by Django 5.0.1 on 2024-03-14 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_poll_votes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='votes',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
