# Generated by Django 5.0.1 on 2024-02-05 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0004_alter_poll_date_to_close'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='date_to_close',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='is_closed',
        ),
        migrations.AlterField(
            model_name='poll',
            name='description',
            field=models.CharField(max_length=400),
        ),
    ]
