# Generated by Django 5.0.1 on 2024-02-09 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0006_alter_poll_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poll',
            options={'ordering': ['-created']},
        ),
    ]
