# Generated by Django 5.0.1 on 2024-02-09 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0007_alter_poll_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='title',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='poll',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
