# Generated by Django 5.0.1 on 2024-02-10 08:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0008_poll_title_alter_poll_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='user_votes',
            field=models.ManyToManyField(related_name='voted_for', to=settings.AUTH_USER_MODEL),
        ),
    ]
